#!/usr/bin/perl
use strict;
use warnings;
use ExtUtils::Installed;

my $inst    = ExtUtils::Installed->new();
my @modules = $inst->modules();

for my $module (@modules) {
    print "$module ------ ", `perldoc -m $module | grep 'VERSION '`, "\n";
}
# print join("\n",@modules), "\n";
1;
